Loaded dependency [numpy/1.26.2-python-3.10.13-openblas-0.3.25]: openblas/0.3.25
Loaded dependency [python3/3.10.13]: gcc/11.4.0-binutils-2.40
Loaded dependency [python3/3.10.13]: sqlite3/3.44.2
Loaded dependency [numpy/1.26.2-python-3.10.13-openblas-0.3.25]: python3/3.10.13
Loaded dependency [pandas/2.1.3-python-3.10.13]: numpy/1.26.2-python-3.10.13-openblas-0.3.25
Loaded module: pandas/2.1.3-python-3.10.13

Loading pandas/2.1.3-python-3.10.13
  Loading requirement: openblas/0.3.25 gcc/11.4.0-binutils-2.40 sqlite3/3.44.2
    python3/3.10.13 numpy/1.26.2-python-3.10.13-openblas-0.3.25
Loaded dependency [h5py/3.10.0-python-3.10.13]: hdf5/1.12.2-gcc-11.3.0
Loaded module: h5py/3.10.0-python-3.10.13

Loading h5py/3.10.0-python-3.10.13
  Loading requirement: hdf5/1.12.2-gcc-11.3.0
/dtu-compute/HCP_dFC/2023/hcp_dfc/src/DMM_EM/ACGEM.py:27: RuntimeWarning: divide by zero encountered in divide
  log_det_D = np.sum(np.log(1/S1**2+1),axis=-1)+2*np.sum(np.log(S1),axis=-1)
/dtu-compute/HCP_dFC/2023/hcp_dfc/src/DMM_EM/ACGEM.py:27: RuntimeWarning: divide by zero encountered in log
  log_det_D = np.sum(np.log(1/S1**2+1),axis=-1)+2*np.sum(np.log(S1),axis=-1)
/dtu-compute/HCP_dFC/2023/hcp_dfc/src/DMM_EM/ACGEM.py:27: RuntimeWarning: invalid value encountered in add
  log_det_D = np.sum(np.log(1/S1**2+1),axis=-1)+2*np.sum(np.log(S1),axis=-1)
/dtu-compute/HCP_dFC/2023/hcp_dfc/src/DMM_EM/DMMEMBaseModel.py:259: RuntimeWarning: invalid value encountered in reduce
  logsum_density = np.logaddexp.reduce(log_density) #sum over the K components
Traceback (most recent call last):
  File "/dtu-compute/HCP_dFC/2023/hcp_dfc/experiments2/experiment_sequential_init_100.py", line 93, in <module>
    run_experiment(extraoptions=options,suppress_output=True)
  File "/dtu-compute/HCP_dFC/2023/hcp_dfc/experiments2/experiment_sequential_init_100.py", line 82, in run_experiment
    params,df = run(data_train=data_train,L_train=L_train,data_test=data_test,L_test=L_test,K=K,df=df,options=options,params=params_MM,suppress_output=suppress_output,inner=inner,p=p)
  File "/dtu-compute/HCP_dFC/2023/hcp_dfc/experiments2/experiment_sequential_init_100.py", line 9, in run
    params,train_posterior,loglik_curve = train_model(data_train,L_train,K=K,options=options,suppress_output=suppress_output,samples_per_sequence=1200,params=params)
  File "/dtu-compute/HCP_dFC/2023/hcp_dfc/src/helper_functions.py", line 71, in train_model
    params,posterior,loglik = mixture_EM_loop(model,data_train,L_train,tol=options['tol'],max_iter=options['max_iter'],
  File "/dtu-compute/HCP_dFC/2023/hcp_dfc/src/DMM_EM/mixture_EM_loop.py", line 39, in mixture_EM_loop
    raise ValueError("Nan reached")
ValueError: Nan reached
